"""
Alembic environment.

Reads the database URL from the app's own settings rather than alembic.ini, so
there is one place a connection string is configured and Railway's injected
DATABASE_URL just works (including the legacy postgres:// rewrite).
"""

from __future__ import annotations

import os
import sys
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.db import DATABASE_URL          # noqa: E402
from app.models_db import Base           # noqa: E402

config = context.config
config.set_main_option("sqlalchemy.url", DATABASE_URL.replace("%", "%%"))

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    context.configure(
        url=DATABASE_URL, target_metadata=target_metadata,
        literal_binds=True, dialect_opts={"paramstyle": "named"},
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def _add_server_defaults(context_, revision, directives):
    """Make autogenerated ADD COLUMN safe on tables that already have rows.

    Autogenerate emits `nullable=False` with no default for a new non-nullable
    column. Postgres (and SQLite in batch mode) reject that on a populated
    table, so the migration fails and rolls back -- silently, if you only read
    the "Running upgrade" line.

    This copies the model's own Python default into a server_default so existing
    rows get a real value. Nothing is guessed: if the model has no usable
    default, the column is made nullable instead of inventing one.
    """
    from alembic.operations import ops

    if not directives:
        return
    script = directives[0]

    def fix(op_):
        col = getattr(op_, "column", None)
        if col is None or col.nullable or col.server_default is not None:
            return
        default = col.default
        if default is not None and not default.is_callable:
            val = default.arg
            # Plain strings, not sa.text(): Alembic's renderer does a
            # truthiness check on server_default, and a TextClause raises
            # "Boolean value of this clause is not defined" mid-generation.
            if isinstance(val, bool):
                col.server_default = "true" if val else "false"
            elif isinstance(val, (int, float)):
                col.server_default = str(val)
            elif isinstance(val, str):
                col.server_default = f"'{val}'"
            else:
                col.nullable = True
        else:
            # no safe default available -- nullable is the honest choice
            col.nullable = True

    def walk(ops_container):
        for op_ in ops_container.ops:
            if isinstance(op_, ops.AddColumnOp):
                fix(op_)
            elif hasattr(op_, "ops"):
                walk(op_)

    for upgrade_ops in script.upgrade_ops_list:
        walk(upgrade_ops)


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.", poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection, target_metadata=target_metadata,
            compare_type=True,
            # SQLite can't ALTER most things in place; batch mode rewrites the
            # table. Harmless on Postgres, essential for local dev.
            render_as_batch=connection.dialect.name == "sqlite",
            process_revision_directives=_add_server_defaults,
            # Don't churn migrations over constraint noise autogenerate reports
            # on SQLite reflection.
            compare_server_default=False,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
