"""baseline schema

Revision ID: 00b4595d0891
Revises: 
Create Date: 2026-07-28 16:40:41.476570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b4595d0891'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('charge_id', sa.String(), nullable=True),
    sa.Column('bill_id', sa.String(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_company'), ['company'], unique=False)

    op.create_table('bills',
    sa.Column('bill_id', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('card_last4', sa.String(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('bill_id')
    )
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bills_company'), ['company'], unique=False)

    op.create_table('cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('last4', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('holder', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('qbo_account_id', sa.String(), nullable=False),
    sa.Column('qbo_account_name', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cards_last4'), ['last4'], unique=False)

    op.create_table('charges',
    sa.Column('charge_id', sa.String(), nullable=False),
    sa.Column('source_txn_id', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('card_last4', sa.String(), nullable=True),
    sa.Column('cardholder_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('merchant', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolution', sa.String(), nullable=False),
    sa.Column('matched_bill_id', sa.String(), nullable=False),
    sa.Column('coded_category', sa.String(), nullable=False),
    sa.Column('coded_vendor', sa.String(), nullable=False),
    sa.Column('resolved_by', sa.String(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('qbo_txn_id', sa.String(), nullable=False),
    sa.Column('qbo_txn_type', sa.String(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('raw_description', sa.Text(), nullable=False),
    sa.Column('is_credit', sa.Boolean(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('charge_id')
    )
    with op.batch_alter_table('charges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_charges_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_charges_qbo_txn_id'), ['qbo_txn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_charges_source_txn_id'), ['source_txn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_charges_status'), ['status'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('hal_records',
    sa.Column('record_id', sa.String(), nullable=False),
    sa.Column('lookup_name', sa.String(), nullable=False),
    sa.Column('holder_name', sa.String(), nullable=False),
    sa.Column('address_book', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('plan_type', sa.String(), nullable=False),
    sa.Column('card_program', sa.String(), nullable=False),
    sa.Column('has_payment_plan', sa.Boolean(), nullable=False),
    sa.Column('statuses_json', sa.Text(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('record_id')
    )
    with op.batch_alter_table('hal_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hal_records_holder_name'), ['holder_name'], unique=False)

    op.create_table('match_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('charge_id', sa.String(), nullable=False),
    sa.Column('bill_id', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reasons', sa.Text(), nullable=False),
    sa.Column('overwrite_bill_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('posted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_results_charge_id'), ['charge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_results_company'), ['company'], unique=False)

    op.create_table('oauth_states',
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('qbo_reference',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('realm_id', sa.String(), nullable=False),
    sa.Column('qbo_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('subtype', sa.String(), nullable=False),
    sa.Column('usable_for', sa.String(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qbo_reference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qbo_reference_kind'), ['kind'], unique=False)

    op.create_table('qbo_tokens',
    sa.Column('realm_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('access_expires_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_expires_at', sa.DateTime(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('realm_id')
    )
    op.create_table('source_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('qbo_account_id', sa.String(), nullable=False),
    sa.Column('qbo_account_name', sa.String(), nullable=False),
    sa.Column('realm_id', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_accounts_company'), ['company'], unique=False)

    op.create_table('sync_status',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('records', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('uploads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('rows_seen', sa.Integer(), nullable=False),
    sa.Column('rows_new', sa.Integer(), nullable=False),
    sa.Column('rows_duplicate', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('uploads')
    op.drop_table('sync_status')
    with op.batch_alter_table('source_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_accounts_company'))

    op.drop_table('source_accounts')
    op.drop_table('qbo_tokens')
    with op.batch_alter_table('qbo_reference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qbo_reference_kind'))

    op.drop_table('qbo_reference')
    op.drop_table('oauth_states')
    with op.batch_alter_table('match_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_results_company'))
        batch_op.drop_index(batch_op.f('ix_match_results_charge_id'))

    op.drop_table('match_results')
    with op.batch_alter_table('hal_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hal_records_holder_name'))

    op.drop_table('hal_records')
    op.drop_table('companies')
    with op.batch_alter_table('charges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_charges_status'))
        batch_op.drop_index(batch_op.f('ix_charges_source_txn_id'))
        batch_op.drop_index(batch_op.f('ix_charges_qbo_txn_id'))
        batch_op.drop_index(batch_op.f('ix_charges_company'))

    op.drop_table('charges')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cards_last4'))

    op.drop_table('cards')
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bills_company'))

    op.drop_table('bills')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_company'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
