"""post state on charges

Revision ID: 0bbf8d37627a
Revises: 62d9ba86318d
Create Date: 2026-07-28 17:27:30.851642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bbf8d37627a'
down_revision: Union[str, Sequence[str], None] = '62d9ba86318d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qbo_sync_token', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('post_error', sa.Text(), server_default='', nullable=False))

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('charges', schema=None) as batch_op:
        batch_op.drop_column('post_error')
        batch_op.drop_column('qbo_sync_token')

    # ### end Alembic commands ###
