"""company registry

Revision ID: 62d9ba86318d
Revises: 6a8fa3fdf41d
Create Date: 2026-07-28 17:13:15.506848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62d9ba86318d'
down_revision: Union[str, Sequence[str], None] = '6a8fa3fdf41d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('realm_id', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('qbo_company_name', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('active', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_companies_realm_id'), ['realm_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_realm_id'))
        batch_op.drop_column('created_at')
        batch_op.drop_column('active')
        batch_op.drop_column('qbo_company_name')
        batch_op.drop_column('realm_id')

    # ### end Alembic commands ###
