"""add learned_rules

Revision ID: 6a8fa3fdf41d
Revises: 00b4595d0891
Create Date: 2026-07-28 17:00:47.065876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a8fa3fdf41d'
down_revision: Union[str, Sequence[str], None] = '00b4595d0891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learned_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('merchant_key', sa.String(), nullable=False),
    sa.Column('sample_merchant', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=False),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('disagreements', sa.Integer(), nullable=False),
    sa.Column('auto_apply', sa.Boolean(), nullable=False),
    sa.Column('last_actor', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learned_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learned_rules_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_learned_rules_merchant_key'), ['merchant_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learned_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learned_rules_merchant_key'))
        batch_op.drop_index(batch_op.f('ix_learned_rules_company'))

    op.drop_table('learned_rules')
    # ### end Alembic commands ###
