"""coded category and vendor ids

Revision ID: a90864e161ae
Revises: 293f01fbb45c
Create Date: 2026-07-28 20:17:25.828635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a90864e161ae'
down_revision: Union[str, Sequence[str], None] = '293f01fbb45c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coded_category_id', sa.String(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('coded_vendor_id', sa.String(), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charges', schema=None) as batch_op:
        batch_op.drop_column('coded_vendor_id')
        batch_op.drop_column('coded_category_id')

    # ### end Alembic commands ###
